import RdfFormFieldsPlanLivingTogetherTableEditComponent from './edit';

export default class RdfFormFieldsPlanLivingTogetherTableShowComponent extends RdfFormFieldsPlanLivingTogetherTableEditComponent {}
