---
kind: pipeline
type: docker
name: test
steps:
- name: install
  image: danlynn/ember-cli:5.2.1-node_18.17
  commands:
  - npm ci
- name: lint:js
  image: danlynn/ember-cli:5.2.1-node_18.17
  commands:
  - npm run lint:js
- name: lint:hbs
  image: danlynn/ember-cli:5.2.1-node_18.17
  commands:
  - npm run lint:hbs
- name: lint:dependencies
  image: danlynn/ember-cli:5.2.1-node_18.17
  commands:
  - ember dependency-lint
- name: test
  image: danlynn/ember-cli:5.2.1-node_18.17
  commands:
  - npm run test:ember
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: build-dry-run
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - development
  event:
    exclude:
      - pull_request

---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag

---
kind: pipeline
type: docker
name: release-controle
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v}-controle
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
    build_args:
      - CONTROLE=true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: z1mn+LhdmJHSXCP9vHnZ9oQ08Qb/YeRa/6lPfO+bgMoJJhXxzF23ug==
---
kind: secret
name: docker_password
data: fzj5Y/x5J+FpdugFb0sXHxQGUI9Q4bYH1/g5B1OeQjPnOlHbkAxoaAZPOOToBsZ0XPF+9K4muGVDm4mRFRjOvw==
---
kind: signature
hmac: 3d68e795d191db5c90625513fde11bd596ef45249ca57d6d055e9f62981cb2b2

...
