steps:
  install:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    commands:
      - npm run lint:hbs
  lint-css:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    commands:
      - npm run lint:css
  lint-formatting:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    commands:
      - npm run lint:format
  dependency-lint:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    commands:
      - ember dependency-lint
  test:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: [lint-js, lint-hbs, lint-css, lint-formatting, dependency-lint]
    commands:
      - npm run test:ember
when:
  - event: pull_request
